spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: student-service

---
server:
  port: 8080
spring:
  cloud:
    config:
      uri: http://localhost:8080
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: student_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/student_management"
    username: postgres
    password: acar
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/